COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
COMPONENT_REQUIRES := ESPressio_Threads ESPressio_Observable ESPressio_Timing

CXXFLAGS += -DESPRESSIO_EVENT
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MAJOR=5
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MINOR=4
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_PATCH=0
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_STRING=\"5.4.0\"

CXXFLAGS += -std=gnu++17
