COMPONENT_ADD_INCLUDEDIRS := src
COMPONENT_SRCDIRS := src
COMPONENT_REQUIRES := ESPressio_Threads ESPressio_Observable ESPressio_Timing

CXXFLAGS += -DESPRESSIO_EVENT
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MAJOR=5
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_MINOR=8
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_PATCH=2
CXXFLAGS += -DESPRESSIO_EVENT_VERSION_STRING=\"5.8.2\"

CXXFLAGS += -std=gnu++17
