name=Flowduino ESPressio-Event
version=5.2.0
author=Simon J. Stuart
maintainer=Flowduino.com
sentence=Event-driven development library for ESP32 microcontrollers
paragraph=Event Pattern components for ESP32-family microcontrollers using Arduino-ESP32, RTTI, ESPressio Threads 3.x, generic typed Event time representations, and optional ESPressio Serializable Event integration.
category=Communication
url=https://github.com/Flowduino/ESPressio-Event
architectures=esp32
includes=ESPressio_Event.hpp,ESPressio_EventThread.hpp,ESPressio_PrecisionEventThread.hpp
depends=ESPressio-Threads (>=3.1.0),Flowduino ESPressio-Observable (>=3.0.0),Flowduino ESPressio-Timing (>=2.2.0)
