name=Flowduino ESPressio-Event
version=4.0.0
author=Simon J. Stuart
maintainer=Flowduino.com
sentence=Event-driven development library for ESP32 microcontrollers
paragraph=Event Pattern components for ESP32-family microcontrollers using the Arduino framework, ESP-IDF FreeRTOS APIs, RTTI, and ESPressio Threads.
category=Communication
url=https://github.com/Flowduino/ESPressio-Event
architectures=esp32
includes=ESPressio_Event.hpp,ESPressio_EventThread.hpp,ESPressio_PrecisionEventThread.hpp
depends=ESPressio-Threads (>=2.0.0),Flowduino ESPressio-Observable (>=3.0.0)
