#pragma once

#include "ESPressio_ThreadManagerEventBridge_Serializable.hpp"
#include "ESPressio_ThreadGarbageCollectorEventBridge_Serializable.hpp"
#include "ESPressio_ThreadTerminationDispatcherEventBridge_Serializable.hpp"
